apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cast
  template:
    metadata:
      labels:
        app: cast
    spec:
      containers:
        - name: cast
          image: "{{ .Values.cast.image.repository }}:{{ .Values.cast.image.tag }}"
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          env:
            - name: DATABASE_URI
              value: "postgresql://appuser:GE4eSstlklbpgDRXDWl2@app-postgresql.{{ .Release.Namespace }}/appdb"
              #value: postgresql://appuser:${DB_PASSWORD}@{{ .Release.Name }}-postgresql/appdb
            #- name: DB_PASSWORD
              #valueFrom:
               # secretKeyRef:
                  #name: app-postgres-secret
                  #key: password
