apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: movie
  template:
    metadata:
      labels:
        app: movie
    spec:
      containers:
        - name: movie
          image: "{{ .Values.movie.image.repository }}:{{ .Values.movie.image.tag }}"
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
          env:
            - name: DATABASE_URI
              #value: postgresql://appuser:$(DB_PASSWORD)@{{ .Release.Name }}-postgresql:5432/appdb
              value: "postgresql://appuser:AppPassword123@app-postgresql.{{ .Release.Namespace }}/appdb"
            #- name: DB_PASSWORD
              #valueFrom:
                #secretKeyRef:
                  #name: app-postgres-secret
                  #key: password
