{{- $existing := lookup "v1" "Secret" .Release.Namespace "app-postgres-secret" }}

apiVersion: v1
kind: Secret
metadata:
  name: app-postgres-secret
type: Opaque
stringData:
  password: {{ if $existing }}{{ index $existing.data "password" | b64dec }}{{ else }}{{ randAlphaNum 20 }}{{ end }}
