replicaCount: 1

movie:
  image:
    repository: welchallch/movie-service
    tag: "1.2"

cast:
  image:
    repository: welchallch/cast-service
    tag: "1.2"

service:
  type: ClusterIP
  port: 8000

postgresql:
  #image:
    #registry: docker.io
    #repository: bitnami/postgresql
    #tag: latest
  auth:
    username: appuser
    password: AppPassword123
    database: appdb
    #existingSecret: app-postgres-secret
  primary:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
    persistence:
      enabled: false
      #size: 1Gi

ingress:
  enabled: true
  className: nginx
  host: ""
