replicaCount: 2

movie:
  image:
    repository: welchallch/movie-service
    tag: "1.2"

cast:
  image:
    repository: welchallch/cast-service
    tag: "1.2"

service:
  type: ClusterIP
  port: 8000

postgres:
  auth:
    username: appuser
    database: appdb
    existingSecret: app-postgres-secret
  primary:
    persistence:
      enabled: true
      size: 1Gi
 #host: postgres.dev.svc.cluster.local
 # port: "5432"
 # db: appdb
 # user: postgres

ingress:
  enabled: true
  className: nginx
  host: ""
